name: Axo
description: "A wellness tracking application with Firebase integration."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Belanosima
      fonts:
        - asset: fonts/Belanosima-Regular.ttf
        - asset: fonts/Belanosima-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "images/mlogo.png"
